### ISSUE TITLE
My extension already supported localization

### ISSUE THREAD

**Issue by stutteringp0et** [sebschlicht/plg_system_eprivacy#1]
You're about a dozen bugfix and feature revisions behind, and there are language files available for download in my forum.

The instructions you've provided will give users the latest version when they download the (now) version 3.8.1 package from me, then downgrade the system plugin to 3.7.3.  The most important part will be 12 revisions behind (as of this red-hot-second).

Since GDPR landed, I release several revisions daily.

This is a very bad idea that can only make both of us look bad.  Someone will download your copy and think my extension is broken, when in reality - you're giving them an outdated revision.

This is a great example of how NOT to fork an extension.  If you plan on maintaining it (and that means not copying my updates, but maintaining your new fork), then you need to take my name off of it.  I don't want the blame when your copy fails to match the features of the latest release of my extension.

**Comment by stutteringp0et** [comment]
You are now 12 bugfixes and 2 feature releases behind

**Comment by sebschlicht** [comment]
You are right, this was a bad idea which I did primarily for myself. I like to document all my projects, regardless if they're only for myself or not, and I placed links to your pages just to respect your authorship. If you don't like that I can remove them. As far as I've understood, this is what you've asked me to.

I see that putting all the files in a localization package is a bad idea if there isn't a particular reason for that. In this case there isn't any. Thus I'll restructure the package to make it a plain localization package, which doesn't downgrade the core files anymore, today.

Though your plugin supports localization in the sense that it uses language keys you don't stick to code conventions. Those ask to place a `language` folder in the package, create subfolders for each language and place the respective languages files inside.

**Comment by sebschlicht** [comment]
Here we go. I've made the package a plain German localization package, no core files will be overridden anymore. If that's fine for you, I'd keep a link to your pages to acknowledge the authorship regarding the actual code. Leave me a note if you'd prefer to not be mentioned at all.

**Comment by stutteringp0et** [comment]
Fantastic!  Sorry if I was rough with my initial comments - I'm fighting to keep my extension ratings up and finding people hosting 2, 3 and 4 year old copies everywhere!
